services:
  web:
    build:
      context: .
    pull_policy: build
    container_name: iccdmt
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 31003
